name: Java CI using Maven

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code checkout from repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and run test cases
      - name: Build and Install
        run: mvn clean install

      # Step 5: Move Allure results to the target folder
      - name: Move Allure Results
        run: mv allure-results target/allure-results

      # Step 6: Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:report

      # Step 7: Upload Allure Report as Artifact
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin